name = input("Введите имя рыцаря: ")
name_zdorov = input("Кол-во здоровья: ")
name_yron = input("урон от его меча: ")
name_zapas = input("Кол-во зелий здоровья: ")
print("Герой по имени", name, "отправляется в сказочное приключение. На его пути встречается мерзкий, злой Гоблин")
name_goblin = input("Имя Гоблина:")
gobli_zdorov = input("Здоровье  Гоблина: ")
goblin_yron = input("Урон здоровья рыцарю: ")
goblin_zapas = input("запас здоровья Гоблина: ")
print("Отважный рыцарь встречает Гоблина  на своём пути. У него", name_goblin, "Здоровья", gobli_zdorov, "а урон от его меча", goblin_yron,)